FROM public.ecr.aws/lambda/provided:al2

# リンカーとしてgcc
RUN yum install -y gcc

# rustupでRUSTツールチェーンをインストール
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
ENV PATH $PATH:/root/.cargo/bin
RUN rustup install stable

VOLUME /code

WORKDIR /code
ENTRYPOINT [ "cargo", "build", "--release" ]